### PR TITLE
[BallerinaToOpenAPI][BuildExtension] Remove special characters from generated OpenAPI file name

### LINKED ISSUE #952: Open API spec generation failing for resourse paths containing '/'
**Description:**

Found that this issue is occuring for every resource with a path containing `/`.

Screenshot from 2022-04-19 11-09-01

But we can generate the openapi spec with the command `bal openapi -i test.bal` though.

Screenshot from 2022-04-19 11-11-34
 

**Steps to reproduce:**

Create an app and edit the resource path as the above screen shot.

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**
https://github.com/wso2-enterprise/choreo/issues/12628

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests - added
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java [hunk 1]
```diff
@@ -477,7 +478,27 @@ public static String getOpenApiFileName(String servicePath, String serviceName,
...
+        String[] splitNames = openAPIFileName.split("[^a-zA-Z0-9]");
+        StringBuilder normalizeFileName = new StringBuilder();
+        for (String name: splitNames) {
+            if (!name.isBlank()) {
+                normalizeFileName.append(name).append(UNDERSCORE);
+            }
+        }
+        if (normalizeFileName.toString().endsWith(UNDERSCORE)) {
+            return normalizeFileName.deleteCharAt(normalizeFileName.length() - 1).toString();
+        }
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java:500]: You can replace the `StringBuilder` with a `StringJoiner` instance for the same purpose, but with less complexity

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java [hunk 2]
```diff
@@ -477,7 +478,27 @@ public static String getOpenApiFileName(String servicePath, String serviceName,
...
-        return openAPIFileName + Constants.OPENAPI_SUFFIX + (isJson ? JSON_EXTENSION : YAML_EXTENSION);
+
+        return getNormalizeFileName(openAPIFileName) + Constants.OPENAPI_SUFFIX +
+                (isJson ? JSON_EXTENSION : YAML_EXTENSION);
+    }
+
+    /**
+     * Remove special characters from the given file name.
+     */
+    public static String getNormalizeFileName(String openAPIFileName) {
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java:489]:
```suggestion
    public static String getNormalizedFileName(String openAPIFileName) {
```

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java [hunk 3]
```diff
@@ -477,7 +478,27 @@ public static String getOpenApiFileName(String servicePath, String serviceName,
...
+
+        String[] splitNames = openAPIFileName.split("[^a-zA-Z0-9]");
+        StringBuilder normalizeFileName = new StringBuilder();
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java:492]:
```suggestion
        StringBuilder normalizedFileName = new StringBuilder();
```

File: openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ServiceDeclarationNodesTests.java [hunk 4]
```diff
@@ -49,23 +49,23 @@ public void setup() throws IOException {
...
         Path ballerinaFilePath = RES_DIR.resolve("multiple_services.bal");
         executedMethod(ballerinaFilePath, "multiple_service_01.yaml", "hello_openapi.yaml",
-                "hello-");
+                "hello_");
     }
 
     @Test(description = "Multiple services with absolute path as '/'. ")
     public void multipleServiceWithOutAbsolute() throws IOException {
         Path ballerinaFilePath = RES_DIR.resolve("multiple_services_without_base_path.bal");
         executedMethod(ballerinaFilePath, "multiple_service_02.yaml",
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ServiceDeclarationNodesTests.java:58]: Should this be `executedMethod` or `executeMethod`? I suppose the latter one sounds correct.

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java (hunk 1 above)
Comment (lnash94) [reply openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java:500]: Yeah , will use `StringJoiner` for the implementation.

File: openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ServiceDeclarationNodesTests.java (hunk 4 above)
Comment (lnash94) [reply openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/ServiceDeclarationNodesTests.java:58]: Yeah I will change with `executeMethod` since the function's purpose is to execute the method.

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java [hunk 5]
```diff
@@ -479,24 +481,20 @@ public static String getOpenApiFileName(String servicePath, String serviceName,
...
-            if (!name.isBlank()) {
-                normalizeFileName.append(name).append(UNDERSCORE);
-            }
-        }
-        if (normalizeFileName.toString().endsWith(UNDERSCORE)) {
-            return normalizeFileName.deleteCharAt(normalizeFileName.length() - 1).toString();
+        if (splitNames.length > 0) {
+            return Arrays.stream(splitNames)
+                    .map(namePart -> namePart)
+                    .collect(Collectors.joining(UNDERSCORE));
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java:497]: Can be simplified as `return String.join(UNDERSCORE, splitNames)`

Comment (lnash94) [reply openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java]: This `splitNames` array contains some time blank items, Therefor we need to add some item validation before joining the string :) .

Comment (NipunaRanasinghe) [reply openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java]: @lnash94 I don't see that blank string validation in here :) Then shall we stick to the steam APIs update the logic accordingly?

Comment (lnash94) [reply openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java]: Please refer to this commit https://github.com/ballerina-platform/openapi-tools/commit/e8c9a6dc5bbf752e40c68af2ea2ef5c6a1b38ed1 🙂

**Review by NipunaRanasinghe — APPROVED** [review]

**Comment by Asitha** [comment]
@lnash94 do we have a specific date we can expect this fix to be released with Ballerina?
