### PR TITLE
[Master] Fix for Create record according to OAS `additionalProperties` when it is available

### LINKED ISSUE #636: Create record according to OAS `additionalProperties`  when it available
**Description:**
Currently, openAPI tool generated Open records for all the given schemas. OAS has a schema field called `additionalProperty`
this field uses to make ware that schema can be allowed to have any field except given properties.
Using that field we can add which type of  record we need to be created for schema

- [ ] When `additionalProperty = true` record should be open record.
```openapi
type: object
properties:
  name:
    type: string
required:
  - name
additionalProperties: true
 
````
or 
```openapi
type: object
properties:
  name:
    type: string
required:
  - name
additionalProperties {}
```
```ballerina
type MySchema record {
    string name;
};
```
- [ ] When `additionalProperties` has special field. 
```openapi
type: object
properties:
  name:
    type: string
required:
  - name
additionalProperties:
  type: string
```
```ballerina
type MySchema record {|
    string name;
    string ...
|};
```
- [ ] when `additionalProperties = false` , record map to open

```openapi
type: object
properties:
  name:
    type: string
required:
  - name
additionalProperties: false
```
```ballerina
type MySchema record {|
    string name;
|};
```
**Describe your problem(s)**

**Describe your solution(s)**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by lnash94**
## Purpose

- > Fix #636  (schema generation)
- Fix for unsupported return type and request type (service generation task with `service package`) commit https://github.com/ballerina-platform/openapi-tools/pull/1117/commits/1c142f49dc353f8c67feee07c566d522a75b55bc 

- Change undefined reference test for parser issue test 
- Update the swagger parser for the latest version 2.1.9 

## Automation tests
 - Unit tests  - Added
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/MapSchemaNegativeTests.java [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+    @BeforeClass
+    public void setUp() {
+        this.console = new ByteArrayOutputStream();
+        this.printStream = new PrintStream(this.console);
+    }
+
+    @Test(expectedExceptions = BallerinaOpenApiException.class,
+    expectedExceptionsMessageRegExp = "OpenAPI definition has errors: \n" +
+            "\n" +
+            "attribute components.schemas.User02.additionalProperties.*")
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/MapSchemaNegativeTests.java:54]: Let's format properly

File: openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/MapSchemaNegativeTests.java [hunk 2]
```diff
@@ -0,0 +1,91 @@
...
+        // This console output check failed due to not receiving generation outstream for test outstream.
+        // Tried with several scenarios by passing printstream through relevant constructors and this outstream
+        // capture doesn't work for integration tests as well. Therefore, these warnings are tested by manually, it
+        // worked as expected.
+        //TODO: update these kind of scenario with proper outstream matching test.
+        String expectedOut = "WARNING: constraints in the OpenAPI contract will be ignored for the " +
+                "additionalProperties field, as constraints are not supported on Ballerina rest record field.\n" +
+                "WARNING: generating Ballerina rest record field will be ignored for the OpenAPI contract " +
+                "additionalProperties type `ComposedSchema`, as it is not supported on Ballerina rest record field.";
+//        Assert.assertEquals(this.console.toString(), expectedOut);
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/MapSchemaNegativeTests.java:82]: Is this intended?

File: openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/AllOfRecordTypeGenerator.java [hunk 3]
```diff
@@ -120,4 +151,65 @@ private List<Node> generateAllOfRecordFields(List<Schema> allOfSchemas) throws B
...
+     * @return
+     */
+    private static RecordRestDescriptorNode getRestDescriptorNodeForAllOf(List<Schema<?>> restSchemas)
+            throws BallerinaOpenApiException {
+        TypeDescriptorNode unionType = getUnionType(restSchemas);
+        return NodeFactory.createRecordRestDescriptorNode(unionType, createToken(ELLIPSIS_TOKEN),
+                createToken(SEMICOLON_TOKEN));
+    }
+
+
```
Comment (NipunaRanasinghe) [inline openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/AllOfRecordTypeGenerator.java:169]: Additional blank line

File: openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/AllOfRecordTypeGenerator.java [hunk 4]
```diff
@@ -120,4 +151,65 @@ private List<Node> generateAllOfRecordFields(List<Schema> allOfSchemas) throws B
...
+     * Creates the UnionType done for a given schema list.
+     *
+     * @param schemas  List of schemas included in additional fields.
+     * @return Union type
+     * @throws BallerinaOpenApiException when unsupported combination of schemas found
+     */
+    private static TypeDescriptorNode getUnionType(List<Schema<?>> schemas) throws BallerinaOpenApiException {
+
+        // TODO: this has issue with generating union type with `string?|int?...
+        // this issue will be address via this issue https://github.com/ballerina-platform/openapi-tools/issues/810
```
Comment (NipunaRanasinghe) [inline openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/AllOfRecordTypeGenerator.java:180]:
```suggestion
        // this will be tracked via https://github.com/ballerina-platform/openapi-tools/issues/810
```

File: openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/MapSchemaNegativeTests.java (hunk 2 above)
Comment (lnash94) [reply openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/MapSchemaNegativeTests.java:82]: Yeah, This is intended. because this error message scenario cannot capture the print stream, tried several approaches and still couldn't get it, therefore commented on this intentionally and will enable this when we provide diagnostic error messages to openapi to ballerina CLI tool. :)

Comment (NipunaRanasinghe) [reply openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/MapSchemaNegativeTests.java:82]: @lnash94 Please update the tests as per the decisions we made during the offline review.

Comment (NipunaRanasinghe) [reply openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/MapSchemaNegativeTests.java:82]: @lnash94 Any update on this?

Comment (lnash94) [reply openapi-cli/src/test/java/io/ballerina/openapi/generators/schema/MapSchemaNegativeTests.java]: with this commit I improved the test as discussed https://github.com/ballerina-platform/openapi-tools/pull/1117/commits/ce08ffba8dedb83082918c81296c51e9d5e9e7d2 . Although this passed a separate test running,  here encounter the test failure during the full build. Still, it is hard to figure out the reason. since we have added a test for code generation comparison for this scenario. Shall I disable outstream capture check? and work on the rest of the improvement with separate PR :) .

**Review by NipunaRanasinghe — APPROVED** [review]
LGTM

File: openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java [hunk 5]
```diff
@@ -750,7 +748,7 @@ public static void validateRequestBody(Set<Map.Entry<String, PathItem>> paths) t
         }
 
         if (!errorList.isEmpty()) {
-            StringBuilder errorMessage = new StringBuilder("OpenAPI definition has errors: " + DOUBLE_LINE_SEPARATOR);
+            StringBuilder errorMessage = new StringBuilder("OpenAPI definition has errors: " + System.lineSeparator());
```
Comment (aneeshafedo) [inline openapi-core/src/main/java/io/ballerina/openapi/core/GeneratorUtils.java:751]: To maintain the consistency. 

```suggestion
            StringBuilder errorMessage = new StringBuilder("OpenAPI definition has errors: " + LINE_SEPARATOR);
```

File: openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/AllOfRecordTypeGenerator.java [hunk 6]
```diff
@@ -98,15 +122,22 @@ private List<Node> generateAllOfRecordFields(List<Schema> allOfSchemas) throws B
         List<Node> recordFieldList = new ArrayList<>();
         for (Schema allOfSchema : allOfSchemas) {
             if (allOfSchema.get$ref() != null) {
+                String extractSchemaName = GeneratorUtils.extractReferenceType(allOfSchema.get$ref());
```
Comment (aneeshafedo) [inline openapi-core/src/main/java/io/ballerina/openapi/core/generators/schema/ballerinatypegenerators/AllOfRecordTypeGenerator.java:125]: To make the variable name a noun. 
```suggestion
                String extractedSchemaName = GeneratorUtils.extractReferenceType(allOfSchema.get$ref());
```
