### PR TITLE
[BallerinaToOAS] Fix for generating OpenAPI specification only for `http:Serivce`

### LINKED ISSUE #749: Give support to generate OpenAPI specification for only `http:Serivce`
**Description:**
Getting support for below scenarios
- [x]  With Service Declaration scenarios 
```ballerina
 service / on new http:Listener(9090) {
      // mock implementation 
 }
```

- [ ] #758 

```ballerina
public service class MyHttpService {
    *http:Service;
    resource function get . () {
        //mock implementation
    } 
}

public function main() returns error? {
    http:Listener l = check new (9090);
    MyHttpService serv = new MyHttpService();
    check l.attach(serv);
}
```
**Describe your problem(s)**
The current Ballerina to OpenAPI tool generate service without checking its service type because tracking the service type is difficult on the previous implementation

**Describe your solution(s)**
Check the service type using services with distinct  that enable after the Ballerina beta4

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests - add
   > Code coverage information
 - Integration tests - add
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java [hunk 1]
```diff
@@ -146,18 +149,29 @@ private static boolean containErrors(List<Diagnostic> diagnostics) {
...
-            // Load a service Node
             if (syntaxKind.equals(SyntaxKind.SERVICE_DECLARATION)) {
-                ServiceDeclarationNode serviceNode = (ServiceDeclarationNode) node;
-                extractServiceDeclarationNodes(serviceName, availableService, servicesToGenerate, serviceNode);
+                /**
+                 * Here check the service is related to the http module by checking listener type that attached to
+                 * service endpoints.
+                 */
+                ServiceDeclarationNode serviceDeclarationNode = (ServiceDeclarationNode) node;
+                Optional<Symbol> serviceSymOptional = semanticModel.symbol(serviceDeclarationNode);
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java:167]:
```suggestion
                Optional<Symbol> serviceSymbol = semanticModel.symbol(serviceDeclarationNode);
```

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java [hunk 2]
```diff
@@ -146,18 +149,29 @@ private static boolean containErrors(List<Diagnostic> diagnostics) {
...
+                if (serviceSymOptional.isPresent()) {
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java:168]:
```suggestion
                if (serviceSymOptional.isPresent() && serviceSymOptional.get() instanceof ServiceDeclarationSymbol) {
```

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java [hunk 3]
```diff
@@ -563,4 +521,22 @@ private static OASResult resolveContractPath(List<OpenAPIConverterDiagnostic> di
         }
         return new OASResult(openAPI, diagnostics);
     }
+
+    private static boolean isListenerBelongsToHttpModule(TypeSymbol listenerType) {
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java:525]:
```suggestion
    private static boolean isHttpListener(TypeSymbol listenerType) {
```

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java [hunk 4]
```diff
@@ -563,4 +521,22 @@ private static OASResult resolveContractPath(List<OpenAPIConverterDiagnostic> di
...
+        }
+
+        if (listenerType.typeKind() == TypeDescKind.TYPE_REFERENCE) {
+            return isHttpModule(((TypeReferenceTypeSymbol) listenerType).typeDescriptor().getModule().get());
+        }
+        return false;
+    }
+
+    private static boolean isHttpModule(ModuleSymbol moduleSymbol) {
+        return HTTP.equals(moduleSymbol.getName().get()) && BALLERINA.equals(moduleSymbol.id().orgName());
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java:540]: `moduleSymbol.getName()` can be empty in here

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java [hunk 5]
```diff
@@ -108,7 +115,8 @@ public void generateOAS3DefinitionsAllService(Path servicePath, Path outPath, St
                         } else {
                             content = definition.getYaml();
                         }
-                        CodegenUtils.writeFile(outPath.resolve(definition.getServiceName()), content.get());
+                        String fileName = checkDuplicateFiles(outPath, definition.getServiceName(), needJson);
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java:118]: IMO using a method name like `resolveContractFileName` would be more meaningful. WDYT?

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java [hunk 6]
```diff
@@ -120,4 +128,57 @@ public void generateOAS3DefinitionsAllService(Path servicePath, Path outPath, St
...
+            }
+        }
+        return openApiName;
+    }
+
+    private static String checkAvailabilityOfGivenName(String openApiName, File[] listFiles, Boolean isJson) {
+        for (File file : listFiles) {
+            if (System.console() != null && file.getName().equals(openApiName)) {
+                String userInput = System.console().readLine("There is already a/an " + file.getName() +
+                        " in the location. Do you want to override the file? [y/N] ");
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java:153]:
```suggestion
                        " in the target location. Do you want to overwrite the file? [y/N] ");
```

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java [hunk 7]
```diff
@@ -120,4 +128,57 @@ public void generateOAS3DefinitionsAllService(Path servicePath, Path outPath, St
...
+    }
+
+    /**
+     * This method for setting the file name for generated file.
+     *
+     * @param listFiles      generated files
+     * @param fileName       File name
+     * @param duplicateCount add the tag with duplicate number if file already exist
+     */
+    private static String setGeneratedFileName(File[] listFiles, String fileName, int duplicateCount, boolean isJson) {
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java:170]: Do we need to pass `duplicateCount` as a parameter? It seems it can be converted to a method-local variable

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java [hunk 8]
```diff
@@ -120,4 +128,57 @@ public void generateOAS3DefinitionsAllService(Path servicePath, Path outPath, St
...
+        for (File listFile : listFiles) {
+            String listFileName = listFile.getName();
+            if (listFileName.contains(".") && ((listFileName.split("\\.")).length >= 2)
+                    && (listFileName.split("\\.")[0]
+                    .equals(fileName.split("\\.")[0]))) {
+                duplicateCount = 1 + duplicateCount;
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java:176]:
```suggestion
                duplicateCount++;
```

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java [hunk 9]
```diff
@@ -120,4 +128,57 @@ public void generateOAS3DefinitionsAllService(Path servicePath, Path outPath, St
...
+            }
+        }
+        if (isJson) {
+            return fileName.split("\\.")[0] + "." + (duplicateCount) + JSON_EXTENSION;
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java:180]:
```suggestion
            return fileName.split("\\.")[0] + "." + duplicateCount + JSON_EXTENSION;
```

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java [hunk 10]
```diff
@@ -120,4 +128,57 @@ public void generateOAS3DefinitionsAllService(Path servicePath, Path outPath, St
...
+        }
+        return fileName.split("\\.")[0] + "." + (duplicateCount) + YAML_EXTENSION;
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java:182]:
```suggestion
        return fileName.split("\\.")[0] + "." + duplicateCount + YAML_EXTENSION;
```

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java [hunk 11]
```diff
@@ -120,4 +128,57 @@ public void generateOAS3DefinitionsAllService(Path servicePath, Path outPath, St
...
+        }
+        return openApiName;
+    }
+
+    private static String checkAvailabilityOfGivenName(String openApiName, File[] listFiles, Boolean isJson) {
+        for (File file : listFiles) {
+            if (System.console() != null && file.getName().equals(openApiName)) {
+                String userInput = System.console().readLine("There is already a/an " + file.getName() +
+                        " in the location. Do you want to override the file? [y/N] ");
+                if (!Objects.equals(userInput.toLowerCase(Locale.ENGLISH), "y")) {
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java:154]: If the user wants to overwrite the file, shouldn't we just replace the exiting file with the new content?

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java (hunk 4 above)
Comment (lnash94) [reply openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java:540]: Currently, we were unable to find the module name empty scenario. yeah,  It is better to add a check for module name availability. I will add

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java (hunk 5 above)
Comment (lnash94) [reply openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java:118]: Yeah, It would be fine.

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java (hunk 11 above)
Comment (lnash94) [reply openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java:154]: Yeah, if the user needs to overwrite the file. we will replace old content with new content by creating a new file with the same name with new content.

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java [hunk 12]
```diff
@@ -120,4 +128,56 @@ public void generateOAS3DefinitionsAllService(Path servicePath, Path outPath, St
...
+            }
+        }
+        return openApiName;
+    }
+
+    private static String checkAvailabilityOfGivenName(String openApiName, File[] listFiles, Boolean isJson) {
+        for (File file : listFiles) {
+            if (System.console() != null && file.getName().equals(openApiName)) {
+                String userInput = System.console().readLine("There is already a/an " + file.getName() +
+                        " in the target location. Do you want to overwrite the file? [y/N] ");
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/openapi/OpenApiConverter.java:153]:
```suggestion
                String userInput = System.console().readLine("There is already a file named '" + file.getName() +
                        "' in the target location. Do you want to overwrite the file? [y/N] ");
```

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java [hunk 13]
```diff
@@ -146,18 +149,28 @@ private static boolean containErrors(List<Diagnostic> diagnostics) {
...
-                ServiceDeclarationNode serviceNode = (ServiceDeclarationNode) node;
-                extractServiceDeclarationNodes(serviceName, availableService, servicesToGenerate, serviceNode);
+                /**
+                 * Here check the service is related to the http module by checking listener type that attached to
+                 * service endpoints.
+                 */
+                ServiceDeclarationNode serviceDeclarationNode = (ServiceDeclarationNode) node;
+                Optional<Symbol> serviceSymbol = semanticModel.symbol(serviceDeclarationNode);
+                if (serviceSymbol.isPresent() && serviceSymbol.get() instanceof ServiceDeclarationSymbol) {
+                    List<TypeSymbol> listenerTypes = ((ServiceDeclarationSymbol) serviceSymbol.get()).listenerTypes();
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java:169]: IMO we better move all these logic into the util function, so that we can simply validate services just by passing the service node. WDYT?

Comment (lnash94) [reply openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java:169]: Here `isHttpListener` function is validated by looking at the listener type of service node whether it is http service or not, hereafter we have to pass this ` serviceName, availableService, servicesToGenerate ` arguments to fill the available services in case the user has added the wrong service name to command to generate spec and return the error message with available services.  `servicesToGenerate` need to store every possible service nodes in one ballerina file to generate spec when a user hasn't mentioned specific service to generate. 
Hope we can simplify this with upcoming improvements, Shall I try to simplify this with improvements 🙂

Comment (NipunaRanasinghe) [reply openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java:169]: sure 🙂

**Review by NipunaRanasinghe — APPROVED** [review]
