### PR TITLE
[Validator] Fix OpenAPI validator duplicates validation when the service file has multiple service node

### LINKED ISSUE #792: OpenAPI validator duplicate validation when the service file has multiple service node
**Description:**
```ballerina
import ballerina/http;
import ballerina/openapi;

@openapi:ServiceInfo {
    contract: "openapiwetherMap.yaml",
    tags: [ ],
    operations:[],
    failOnErrors: false
}
service /data/'2\.5 on new http:Listener(9091) {
    resource function get weather(string? id, string? lat, string? lon, string? zip, string? units, string? lang, string? mode) returns string {
        return "hello";
    }
    resource function get onecall(string lat, string lon, string? exclude, string? units, string? lang) returns string {
        return "hello";
    }
}

service /mVersion on new http:Listener(9090) {
    resource function get versions() returns string {
        return "Hello, World!";
    }
}
```
**output**
```
Compiling source
        hansani/validator:0.1.0
WARNING [openapi_weather.bal:(4:1,17:2)] Couldnt find q parameter in the Ballerina service resource for the method get of the path /weather which is documented in the OpenAPI contract.
WARNING [openapi_weather.bal:(4:1,17:2)] Couldnt find q parameter in the Ballerina service resource for the method get of the path /weather which is documented in the OpenAPI contract.
WARNING [openapi_weather.bal:(4:1,17:2)] Couldnt find q parameter in the Ballerina service resource for the method get of the path /weather which is documented in the OpenAPI contract.
WARNING [openapi_weather.bal:(4:1,17:2)] Couldnt find q parameter in the Ballerina service resource for the method get of the path /weather which is documented in the OpenAPI contract.
```
**Steps to reproduce:**

**Affected Versions:**
SwanLake beta6 rc1
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests - added
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-integration-tests/src/test/java/io/ballerina/openapi/extension/build/ValidatorTests.java [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+        TestUtil.cleanDistribution();
+    }
+
+    @Test(description = "OpenAPI validator plugin test for multiple services")
+    public void testMultipleServices() throws IOException {
+        List<String> buildArgs = new LinkedList<>();
+        buildArgs.add("project_1");
+        InputStream successful = TestUtil.executeOpenapiBuild(DISTRIBUTION_FILE_NAME, TEST_RESOURCE, buildArgs);
+        String msg = " ERROR [service.bal:(4:1,19:2)] Could not find q parameter in the Ballerina service " +
+                "resource for the method get of the path /weather which is documented in the OpenAPI contract";
```
Comment (NipunaRanasinghe) [inline openapi-integration-tests/src/test/java/io/ballerina/openapi/extension/build/ValidatorTests.java:41]:
```suggestion
        String msg = " ERROR [service.bal:(4:1,19:2)] Missing OpenAPI contract parameter 'q' in the counterpart Ballerina service resource (method: 'get', path: '/weather')";
```

File: openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/OpenApiConverterUtilsTest.java [hunk 2]
```diff
@@ -166,7 +166,7 @@ public void testForCompilerWarning() throws IOException {
         TestUtils.compareWithGeneratedFile(ballerinaFilePath, "compiler_warning.yaml");
     }
 
-    @Test(description = "Test for non http services")
+    @Test(description = "Test for non http services", enabled = false)
```
[the remark this answers is not in the document]
Comment (lnash94) [reply openapi-cli/src/test/java/io/ballerina/openapi/generators/openapi/OpenApiConverterUtilsTest.java:169]: This should enable, due to the caching issue this test was failed in local machine, I will enable this :)

File: openapi-integration-tests/src/test/java/io/ballerina/openapi/extension/build/ValidatorTests.java [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+        TestUtil.cleanDistribution();
+    }
+
+    @Test(description = "OpenAPI validator plugin test for multiple services")
+    public void testMultipleServices() throws IOException {
+        List<String> buildArgs = new LinkedList<>();
+        buildArgs.add("project_1");
+        InputStream successful = TestUtil.executeOpenapiBuild(DISTRIBUTION_FILE_NAME, TEST_RESOURCE, buildArgs);
+        String msg = " ERROR [service.bal:(4:1,19:2)] Missing OpenAPI contract parameter `q` in the counterpart" +
+                " Ballerina service resource (method: `get`, path: `/weather`)";
```
Comment (NipunaRanasinghe) [inline openapi-integration-tests/src/test/java/io/ballerina/openapi/extension/build/ValidatorTests.java:58]:
```suggestion
        String msg = " ERROR [service.bal:(4:1,19:2)] Missing OpenAPI contract parameter 'q' in the counterpart" +
                " Ballerina service resource (method: 'get', path: '/weather')";
```

**Review by NipunaRanasinghe — APPROVED** [review]
