### PR TITLE
Fix issue with invalid OpenAPI definition that refers to an undefined schema

### LINKED ISSUE #873: OpenAPI to Ballerina generation crashes for an invalid OpenAPI definition that refers to an undefined schema
**Description:**
$title. We should log a proper error instead?

**Steps to reproduce:**
```yml
openapi: "3.0.0"
info:
  version: 1.0.0
  title: People
paths:
  /person:
    get:
      operationId: getPerson
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The person with the given name.          
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
components:
  schemas:
    Person:
      required:
      - name
      type: object
      properties:
        name:
          type: string
        employee:
          $ref: '#/components/schemas/Employee' # undefined
```

```log
$ bal openapi -i foo.yml -o tempopenapi
ballerina: Oh no, something really went wrong. Bad. Sad.

We appreciate it if you can report the code that broke Ballerina in
https://github.com/ballerina-platform/ballerina-lang/issues with the
log you get below and your sample code.

We thank you for helping make us better.

[2022-01-24 09:41:00,667] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.openapi.generators.schema.TypeGeneratorUtils.getNullableType(TypeGeneratorUtils.java:127)
        at io.ballerina.openapi.generators.schema.ballerinatypegenerators.ReferencedTypeGenerator.generateTypeDescriptorNode(ReferencedTypeGenerator.java:65)
        at io.ballerina.openapi.generators.schema.TypeGeneratorUtils.addRecordFields(TypeGeneratorUtils.java:151)
        at io.ballerina.openapi.generators.schema.ballerinatypegenerators.RecordTypeGenerator.generateTypeDescriptorNode(RecordTypeGenerator.java:87)
        at io.ballerina.openapi.generators.schema.ballerinatypegenerators.TypeGenerator.generateTypeDefinitionNode(TypeGenerator.java:67)
        at io.ballerina.openapi.generators.schema.BallerinaTypesGenerator.getTypeDefinitionNode(BallerinaTypesGenerator.java:136)
        at io.ballerina.openapi.generators.schema.BallerinaTypesGenerator.generateSyntaxTree(BallerinaTypesGenerator.java:102)
        at io.ballerina.openapi.cmd.CodeGenerator.generateBallerinaService(CodeGenerator.java:608)
        at io.ballerina.openapi.cmd.CodeGenerator.generateBalSource(CodeGenerator.java:269)
        at io.ballerina.openapi.cmd.CodeGenerator.generateBothFiles(CodeGenerator.java:159)
        at io.ballerina.openapi.cmd.OpenApiCmd.generateBothFiles(OpenApiCmd.java:361)
        at io.ballerina.openapi.cmd.OpenApiCmd.openApiToBallerina(OpenApiCmd.java:254)
        at io.ballerina.openapi.cmd.OpenApiCmd.execute(OpenApiCmd.java:157)
        at java.base/java.util.Optional.ifPresent(Optional.java:183)
        at io.ballerina.cli.launcher.Main.main(Main.java:51)
```

**Affected Versions:**
2201.0.0-rc1

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests  - added
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/ballerinatypegenerators/ReferencedTypeGenerator.java [hunk 1]
```diff
@@ -62,6 +62,10 @@ public TypeDescriptorNode generateTypeDescriptorNode() throws BallerinaOpenApiEx
         String typeName = getValidName(extractReferenceType(schema.get$ref()), true);
         Schema<?> refSchema = GeneratorMetaData.getInstance().getOpenAPI().getComponents().getSchemas().get(typeName);
         TypeDescriptorNode typeDescriptorNode = createSimpleNameReferenceNode(createIdentifierToken(typeName));
+        if (refSchema == null) {
+            throw new BallerinaOpenApiException(String.format("'%s' $refs must reference a valid location in" +
+                    " the OpenAPI document.", typeDescriptorNode.toString().trim()));
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/ballerinatypegenerators/ReferencedTypeGenerator.java:67]: Shall we indicate `schema.get$ref()` instead of the `typeDescriptorNode` in the error message?

File: openapi-cli/src/test/resources/generators/schema/swagger/undocument_ref.yaml [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+          required: true
+          schema:
+            type: string
+      responses:
+        '200':
+          description: The person with the given name.
+          content:
+            application/json:
+              schema:
+                $ref: '#/components/schemas/Person'
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/resources/generators/schema/swagger/undocument_ref.yaml:23]: Should we add a test for $ref validation in the responses as well?

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/ballerinatypegenerators/ReferencedTypeGenerator.java (hunk 1 above)
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/ballerinatypegenerators/ReferencedTypeGenerator.java:67]:
```suggestion
            throw new BallerinaOpenApiException(String.format("undefined $ref: '%s' in openAPI contract.", typeDescriptorNode.toString().trim()));
```

File: openapi-cli/src/test/resources/generators/schema/swagger/undocument_ref.yaml (hunk 2 above)
Comment (lnash94) [reply openapi-cli/src/test/resources/generators/schema/swagger/undocument_ref.yaml:23]: yeah , we already added the check parser issue , it covered responses as well https://github.com/ballerina-platform/openapi-tools/blob/master/openapi-cli/src/test/java/io/ballerina/openapi/generators/common/SwaggerParserTests.java , current swaggerparser validate response and the requestbody validations but not component schema validation :)

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/ballerinatypegenerators/ReferencedTypeGenerator.java (hunk 1 above)
Comment (lnash94) [reply openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/ballerinatypegenerators/ReferencedTypeGenerator.java:67]: Yeah sure, will change :)

**Review by NipunaRanasinghe — APPROVED** [review]
