### PR TITLE
[Service] Fix issue with Path parameter is not generated for path name key 

### LINKED ISSUE #876: Path parameter is not generated for path name `key`
**Description:**
When a path parameter is given in the name of `key`, that path parameter is not generated in the service resource function.

**Steps to reproduce:**
Generate Ballerina service for following openapi
```yaml
openapi: 3.0.1
info:
  title: Storage Space
  version: 1.0.0
paths:
  /storage-spaces/{storageSpaceName}/keys/{key}:
    get:
      summary: Get key value
      operationId: getKey
      parameters:
        - name: storageSpaceName
          in: path
          description: name of the storage space
          required: true
          schema:
            type: string
        - name: key
          in: path
          description: name of the key to retrieve the value
          required: true
          schema:
            type: string
      responses:
        200:
          description: successful operation
          content:
            text/plain:
              schema:
                type: string
        400:
          description: Invalid key supplied
security:
- authorization: []
components:
  securitySchemes:
    authorization:
      type: apiKey
      description: Represents API Key `authorization`
      name: Authorization
      in: header
```

Generated code
```ballerina
import ballerina/http;

listener http:Listener ep0 = new (9090, config = {host: "localhost"});

service / on ep0 {
    resource function get 'storage\-spaces/[string  storageSpaceName]/keys() returns string|http:BadRequest {
    }
}
```

**Affected Versions:**
SL Beta6

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests - added
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ParameterGeneratorTest.java [hunk 1]
```diff
@@ -99,6 +99,15 @@ public void generatePathparameter02() throws IOException, BallerinaOpenApiExcept
         CommonTestFunctions.compareGeneratedSyntaxTreewithExpectedSyntaxTree("path_parameters02.bal", syntaxTree);
     }
 
+    @Test(description = "When the multiple path parameter has key word as a path parameter")
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/java/io/ballerina/openapi/generators/service/ParameterGeneratorTest.java:102]:
```suggestion
    @Test(description = "Tests when path parameter(s) having a keyword as the parameter name")
```

**Review by NipunaRanasinghe — APPROVED** [review]
LGTM
