### PR TITLE
[Service] Fix OpenAPI header mapping in resource function

### LINKED ISSUE #425: Improve OpenAPI header mapping in resource function
**Description:**
Ballerina language contains three types of main parameter types: required, defaultable, rest. We need to improve our header parameter mapping by aligning to the ballerina parameter.

- [x] OpenAPI has optional header parameter
- [x] OpenAPI has header parameter with default value
- [x] OpenAPI has header parameter with nullable true

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by lnash94**

### CODE REVIEW

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ParametersGenerator.java [hunk 1]
```diff
@@ -141,30 +151,36 @@ public boolean isNullableRequired() {
 
     /**
      * This function for generating parameter ST node for header.
+     * <pre> resource function get pets(@http:Header {name:"x-request-id"} string header) </pre>
      */
-    private RequiredParameterNode handleHeader(Parameter parameter)throws BallerinaOpenApiException {
+    private Node handleHeader(Parameter parameter)throws BallerinaOpenApiException {
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ParametersGenerator.java:156]: Can we modify this to return a `ParameterNode` instead?

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ParametersGenerator.java [hunk 2]
```diff
@@ -174,16 +190,51 @@ private RequiredParameterNode handleHeader(Parameter parameter)throws BallerinaO
                         SINGLE_WS_MINUTIAE));
             }
             // Create annotation for header
-            MappingConstructorExpressionNode annotValue = NodeFactory.createMappingConstructorExpressionNode(
-                    createToken(SyntaxKind.OPEN_BRACE_TOKEN), NodeFactory.createSeparatedNodeList(),
-                    createToken(SyntaxKind.CLOSE_BRACE_TOKEN));
-            AnnotationNode headerNode = getAnnotationNode("Header", annotValue);
-            NodeList<AnnotationNode> headerAnnotations = NodeFactory.createNodeList(headerNode);
+            // This code block is to be enabled when handle the headers handle additional parameters
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ParametersGenerator.java:193]: Lets convert this to a `Todo` and mention the related Github issue

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ServiceDiagnosticMessages.java [hunk 3]
```diff
@@ -31,10 +31,20 @@
...
     OAS_SERVICE_101("OAS_SERVICE_101",
             "Query parameters with no array item type can not be mapped to Ballerina resource" +
-                    " query parameters.",
-            DiagnosticSeverity.ERROR),
+                    " query parameters.", DiagnosticSeverity.ERROR),
     OAS_SERVICE_102("OAS_SERVICE_102",
             "Query parameters with type '%s' can not be mapped to the Ballerina query parameters.",
+            DiagnosticSeverity.ERROR),
+    OAS_SERVICE_103("OAS_SERVICE_103", "Header '%s' with '%s' array item type are not " +
+            "supported in Ballerina.", DiagnosticSeverity.ERROR),
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ServiceDiagnosticMessages.java:39]:
```suggestion
    OAS_SERVICE_103("OAS_SERVICE_103", "Header '%s' with array item type: '%s' is not " +
            "supported in Ballerina.", DiagnosticSeverity.ERROR),
```

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ServiceDiagnosticMessages.java [hunk 4]
```diff
@@ -31,10 +31,20 @@
...
+    OAS_SERVICE_104("OAS_SERVICE_104",
+            "Header '%s' with no array item type can not be mapped to Ballerina resource" +
+                    " header.", DiagnosticSeverity.ERROR),
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ServiceDiagnosticMessages.java:42]:
```suggestion
            "Header '%s' with no array item type can not be mapped as a valid Ballerina" +
                    " header parameter.", DiagnosticSeverity.ERROR),
```

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ServiceDiagnosticMessages.java [hunk 5]
```diff
@@ -31,10 +31,20 @@
...
+    OAS_SERVICE_105("OAS_SERVICE_105",
+            "Header '%s' with type '%s' can not be mapped to the Ballerina headers.",
+            DiagnosticSeverity.ERROR),
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ServiceDiagnosticMessages.java:45]:
```suggestion
            "Header '%s' with type '%s' can not be mapped as a valid Ballerina header parameter.",
            DiagnosticSeverity.ERROR),
```

File: openapi-cli/src/test/java/io/ballerina/openapi/generators/service/QueryParameterTests.java [hunk 6]
```diff
@@ -197,4 +197,13 @@ public void queryParameterOrder() throws IOException, BallerinaOpenApiException
         syntaxTree = ballerinaServiceGenerator.generateSyntaxTree();
         CommonTestFunctions.compareGeneratedSyntaxTreewithExpectedSyntaxTree("query/query_14.bal", syntaxTree);
     }
+
+    @Test(description = "14. Fix the optional query parameter")
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/java/io/ballerina/openapi/generators/service/QueryParameterTests.java:201]:
```suggestion
    @Test(description = "14. Optional query parameter")
```

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ParametersGenerator.java [hunk 7]
```diff
@@ -141,30 +151,36 @@ public boolean isNullableRequired() {
...
-                headerTypeName = createBuiltinSimpleNameReferenceNode(null, createIdentifierToken(STRING,
-                        SINGLE_WS_MINUTIAE, SINGLE_WS_MINUTIAE));
+                throw new BallerinaOpenApiException(String.format(OAS_SERVICE_105.getDescription(),
+                        parameter.getName(), schema.getType()));
             } else if (schema instanceof ArraySchema) {
-                String arrayType = ((ArraySchema) schema).getItems().getType();
+                Schema<?> items = ((ArraySchema) schema).getItems();
+                if (items.getType() == null) {
+                    throw new BallerinaOpenApiException(String.format(OAS_SERVICE_104.getDescription(),
+                            parameter.getName()));
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ParametersGenerator.java:177]: We better move this into an openAPI error creation API, where you can just pass the error enum value and the args instead of repeating this lengthy code everytime we create an error. ( But we don't need to do it now, lets add it to your planed action items :) )

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ServiceDiagnosticMessages.java [hunk 8]
```diff
@@ -31,10 +31,20 @@
             "supported in Ballerina.", DiagnosticSeverity.ERROR),
     OAS_SERVICE_101("OAS_SERVICE_101",
             "Query parameters with no array item type can not be mapped to Ballerina resource" +
-                    " query parameters.",
-            DiagnosticSeverity.ERROR),
+                    " query parameters.", DiagnosticSeverity.ERROR),
     OAS_SERVICE_102("OAS_SERVICE_102",
             "Query parameters with type '%s' can not be mapped to the Ballerina query parameters.",
+            DiagnosticSeverity.ERROR),
+    OAS_SERVICE_103("OAS_SERVICE_103", "Header '%s' with '%s' array item type are not " +
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ServiceDiagnosticMessages.java:38]: Shouldnt we use `''%s''` syntax for the template args?

File: openapi-cli/src/test/java/io/ballerina/openapi/generators/service/HeaderParameterTests.java [hunk 9]
```diff
@@ -0,0 +1,161 @@
...
+            expectedExceptions = BallerinaOpenApiException.class,
+            expectedExceptionsMessageRegExp = "Header 'x-request-id' with no array item type can not be" +
+                    " mapped to Ballerina.*")
+    public void headerNoItemType() throws IOException, BallerinaOpenApiException {
+        Path definitionPath = RES_DIR.resolve("swagger/headers/header_04.yaml");
+        OpenAPI openAPI = GeneratorUtils.getOpenAPIFromOpenAPIV3Parser(definitionPath);
+        BallerinaServiceGenerator ballerinaServiceGenerator = new BallerinaServiceGenerator(openAPI, filter);
+        syntaxTree = ballerinaServiceGenerator.generateSyntaxTree();
+        CommonTestFunctions.compareGeneratedSyntaxTreewithExpectedSyntaxTree("headers/header.bal", syntaxTree);
+    }
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/java/io/ballerina/openapi/generators/service/HeaderParameterTests.java:85]: We better separate negative test cases from the positive ones as a general practice :) lets add it to your todo items

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ServiceDiagnosticMessages.java (hunk 8 above)
Comment (lnash94) [reply openapi-cli/src/main/java/io/ballerina/openapi/generators/service/ServiceDiagnosticMessages.java:38]: Yeah we need to use `''%s''` but this error message append to OpenAPIExeption message due to that it didn't ignore first `'` 
here. I will change this into `''%s''` once we will use diagnostic error handling. 🙂

**Review by NipunaRanasinghe — APPROVED** [review]
