### PR TITLE
[BallerinaToOAS] Fix issue with generating OAS when services have same absolute base path in service declaration nodes

### LINKED ISSUE #762: Ballerina to OAS command generates one OAS for multiple  service node when services have same absolute base path in service declaration node
**Description:**
When the one service bal file contains multiple service nodes with the same absolute path it will return one contract instead of generating multiple contracts.

**Steps to reproduce:**
**Run the command :** bal openapi -i services.bal
Tested bal file(services.bal):
```ballerina
import ballerina/http;
service / on new http:Listener(9091) {
    resource function get . () {
    }
    resource function get pet(int id) returns string {
        return "hello world";
    }
}
service / on new http:Listener(9092) {
    resource function get . () {
    }
}
```
Generated OpenAPI spec 
```
openapi: 3.0.1
info:
  title: Service Openapi Yaml
  version: 0.1.0
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9092"
paths:
  /:
    get:
      operationId: operation_get
      responses:
        "202":
          description: Accepted
components: {}
```
**Affected Versions:**
Swanlake Beta 4
**OS, DB, other environment details and versions:**
JDK 11 , Ubuntu 20.04

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests add
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

### CODE REVIEW

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java [hunk 1]
```diff
@@ -298,4 +313,75 @@ public static String normalizeTitle(String serviceName) {
...
+        } else if (serviceName.startsWith(HYPHEN)) {
+            // serviceName -> service on ep1 {} has multiple service ex: "-33456"
+            cleanedServiceName = FilenameUtils.removeExtension(servicePath) + serviceName;
+        } else {
+            // Remove starting path separate if exists
+            if (serviceName.startsWith(SLASH)) {
+                serviceName = serviceName.substring(1);
+            }
+            // Replace rest of the path separators with hyphen
+            cleanedServiceName = serviceName.replaceAll(SLASH, "_");
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java:380]: The comment implies that the path separators should be replaced with hypens, but the code uses underscores. Which one should be the correct behaviour?

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java [hunk 2]
```diff
@@ -298,4 +313,75 @@ public static String normalizeTitle(String serviceName) {
...
+        } else {
+            return false;
+        }
+    }
+
+    /**
+     * Generate file name with service basePath.
+     */
+    public static String getOpenApiFileName(String servicePath, String serviceName, boolean isJson) {
+        String cleanedServiceName;
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java:362]:
```suggestion
        String openAPIFileName;
```

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java [hunk 3]
```diff
@@ -298,4 +313,75 @@ public static String normalizeTitle(String serviceName) {
...
+            if (serviceName.startsWith(SLASH)) {
+                serviceName = serviceName.substring(1);
+            }
+            // Replace rest of the path separators with hyphen
+            cleanedServiceName = serviceName.replaceAll(SLASH, "_");
+        }
+        if (isJson) {
+            return cleanedServiceName + Constants.OPENAPI_SUFFIX + JSON_EXTENSION;
+        }
+        return cleanedServiceName + Constants.OPENAPI_SUFFIX + YAML_EXTENSION;
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java:385]:
```suggestion
      return cleanedServiceName + Constants.OPENAPI_SUFFIX + (isJson ? JSON_EXTENSION : YAML_EXTENSION);
```

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java [hunk 4]
```diff
@@ -159,38 +152,53 @@ private static void extractListenersAndServiceNodes(String serviceName, List<Str
...
             }
             if (syntaxKind.equals(SyntaxKind.SERVICE_DECLARATION)) {
-                /**
-                 * Here check the service is related to the http module by checking listener type that attached to
-                 * service endpoints.
+                ServiceDeclarationNode serviceNode = (ServiceDeclarationNode) node;
+                /*
+                  Here check the service is related to the http module by checking listener type that attached to
+                  service endpoints.
                  */
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java:159]: Let's use end-of-line comments within the method bodies. Please correct other relevant places as well.

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java [hunk 5]
```diff
@@ -159,38 +152,53 @@ private static void extractListenersAndServiceNodes(String serviceName, List<Str
...
+                          Generated file name for above example -> hello_openapi.yaml, hello_45673_openapi
+                          .yaml
+                         */
+                        String updateServiceName = service;
+                        if (servicesToGenerate.containsKey(service)) {
+                            updateServiceName = service + HYPHEN + serviceSymbol.get().hashCode();
+                        }
+                        if (serviceName != null) {
+                            // Filtering by service name
+                            availableService.add(service);
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java:191]: WDYM by `availableService`? It seems like a list of resolved service nodes to me.

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java [hunk 6]
```diff
@@ -286,17 +272,17 @@ private static String getOpenApiFileName(String servicePath, String serviceName,
...
+          First check the given service node has metadata with annotation details with `openapi:serviceInfo`,
+          if it is there, then {@link #parseServiceInfoAnnotationAttachmentDetails(List, AnnotationNode, Path)}
+          function extracts the annotation details and store details in {@code OpenAPIInfo} model using
+          {@link #updateOpenAPIInfoModel(SeparatedNodeList)} function. If the annotation contains the valid contract
+          path then we complete given OpenAPI specification using annotation details. if not we create new OpenAPI
+          specification and fill openAPI info sections.
+          If the annotation is not in the given service, then we filled the OpenAPI specification info section using
+          package details and title with service base path.
+          After completing these two process we normalized the OpenAPI specification by checking all the info
+          details are completed, if in case not completed, we complete empty fields with default values.
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java:285]: Please move this section to the method description.

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java (hunk 1 above)
Comment (lnash94) [reply openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ConverterCommonUtils.java:380]: It should be underscored,  will change the comments :)

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java (hunk 5 above)
Comment (lnash94) [reply openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java:191]: This is used to store all the http services absolute paths contain in the ballerina file. This list maintains in case some user has provided some specific absolute path that does not exist in the service file for generating contract, then that time we can generate error message by adding all the service name exist in service by using this list details. :)

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java [hunk 7]
```diff
@@ -159,41 +152,49 @@ private static void extractListenersAndServiceNodes(String serviceName, List<Str
...
-                 */
-                ServiceDeclarationNode serviceDeclarationNode = (ServiceDeclarationNode) node;
-                Optional<Symbol> serviceSymbol = semanticModel.symbol(serviceDeclarationNode);
-                if (serviceSymbol.isPresent() && serviceSymbol.get() instanceof ServiceDeclarationSymbol) {
-                    List<TypeSymbol> listenerTypes = ((ServiceDeclarationSymbol) serviceSymbol.get()).listenerTypes();
-                    listenerTypes.stream().filter(ServiceToOpenAPIConverterUtils::isHttpListener)
-                            .forEachOrdered(listenerType -> extractServiceDeclarationNodes(serviceName,
-                                    availableService, servicesToGenerate, serviceDeclarationNode));
+                ServiceDeclarationNode serviceNode = (ServiceDeclarationNode) node;
+                if (isHttpService(serviceNode, semanticModel)) { //Here check the service is related to the http
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java:156]:
```suggestion
                if (isHttpService(serviceNode, semanticModel)) { 
                //Here check the service is related to the http
```

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java [hunk 8]
```diff
@@ -159,41 +152,49 @@ private static void extractListenersAndServiceNodes(String serviceName, List<Str
...
+                    // module by checking listener type that attached to service endpoints.
+                    Optional<Symbol> serviceSymbol = semanticModel.symbol(serviceNode);
+                    if (serviceSymbol.isPresent() && serviceSymbol.get() instanceof ServiceDeclarationSymbol) {
+                        String service = OpenAPIEndpointMapper.ENDPOINT_MAPPER.getServiceBasePath(serviceNode);
+                        String updateServiceName = service; //`String updateServiceName` used to track the service
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java:161]:
```suggestion
                        String updateServiceName = service; 
                        //`String updateServiceName` used to track the service
```

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java [hunk 9]
```diff
@@ -409,9 +387,9 @@ private static OASResult parseServiceInfoAnnotationAttachmentDetails(List<OpenAP
            SeparatedNodeList<MappingFieldNode> fields = content.get().fields();
            if (!fields.isEmpty()) {
                OpenAPIInfo openAPIInfo = updateOpenAPIInfoModel(fields);
-               /**
-                * If in case ballerina file path is getting null, then openAPI specification will be generated for given
-                * services.
+               /*
+                 If in case ballerina file path is getting null, then openAPI specification will be generated for given
+                 services.
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java:392]: Please use EOL comments

**Review by NipunaRanasinghe — APPROVED** [review]
Approved with minor suggestions

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java (hunk 7 above)
Comment (lnash94) [reply openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java:156]: Fix c064856

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java (hunk 8 above)
Comment (lnash94) [reply openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java:161]: Fix c064856

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java (hunk 9 above)
Comment (lnash94) [reply openapi-bal-service/src/main/java/io/ballerina/openapi/converter/utils/ServiceToOpenAPIConverterUtils.java:392]: Fix c064856
