### PR TITLE
[1.4.x]Changed the request Payload type into `byte[]` for MediaType `application/octet-stream` in client generations

### LINKED ISSUE #1188: Change the request Payload type into `byte[]` for MediaType `application/octet-stream` in client generations
**Description:**
As per discussion https://github.com/ballerina-platform/openapi-tools/issues/815#issuecomment-1380055179 current client generations change into byte array
 example openapi
```openapi
openapi: 3.0.0
info:
  title: refComponent
  description: refComponent
  version: 1.0.0
servers:
  - url: http://petstore.{host}.io/v1
    description: The production API server
    variables:
      host:
        default: openapi
        description: this value is assigned by the service provider
  - url: https://{subdomain}.swagger.io:{port}/{basePath}
    description: The production API server
    variables:
      subdomain:
        default: petstore
        description: this value is assigned by the service provider
      port:
        enum:
          - '8443'
          - '443'
        default: '443'
      basePath:
        default: v2
paths:
  /user:
    post:
      summary: Creates a new user.
      responses:
        200:
          description: OK
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
  /payment:
    post:
      summary: Creates a new payment.
      responses:
        200:
          description: OK
      requestBody:
        description: Details of the pet to be purchased
        content:
          application/octet-stream:
            schema:
              $ref: '#/components/schemas/Pet'
components:
  schemas:
    User:
      type: object
      required:
        - userName
      properties:
        userName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
    Pet:
      type: object
      required:
        - userName
      properties:
        userName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
    PetForm:
      type: object
      required:
        - userName
      properties:
        userName:
          type: string
        firstName:
          type: string
        lastName:
          type: string
 ```
Current generation
```ballerina
# Creates a new user.
    #
    # + return - OK 
    resource isolated function post user(string payload) returns http:Response|error {
        string resourcePath = string `/user`;
        http:Request request = new;
        request.setPayload(payload, "application/octet-stream");
        http:Response response = check self.clientEp->post(resourcePath, request);
        return response;
    }
    # Creates a new payment.
    #
    # + payload - Details of the pet to be purchased 
    # + return - OK 
    resource isolated function post payment(Pet payload) returns http:Response|error {
        string resourcePath = string `/payment`;
        http:Request request = new;
        request.setPayload(payload, "application/octet-stream");
        http:Response response = check self.clientEp->post(resourcePath, request);
        return response;
    }
```
expected code generation
```ballerina
# Creates a new user.
    #
    # + return - OK 
    resource isolated function post user(byte[] payload) returns http:Response|error {
        string resourcePath = string `/user`;
        http:Request request = new;
        request.setPayload(payload, "application/octet-stream");
        http:Response response = check self.clientEp->post(resourcePath, request);
        return response;
    }
    # Creates a new payment.
    #
    # + payload - Details of the pet to be purchased 
    # + return - OK 
    resource isolated function post payment(byte[] payload) returns http:Response|error {
        string resourcePath = string `/payment`;
        http:Request request = new;
        request.setPayload(payload, "application/octet-stream");
        http:Response response = check self.clientEp->post(resourcePath, request);
        return response;
    }
```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by lnash94**
Old Generated code
```ballerina
# Creates a new user.
    #
    # + return - OK 
    resource isolated function post user(string payload) returns http:Response|error {
        string resourcePath = string `/user`;
        http:Request request = new;
        request.setPayload(payload, "application/octet-stream");
        http:Response response = check self.clientEp->post(resourcePath, request);
        return response;
    }
    # Creates a new payment.
    #
    # + payload - Details of the pet to be purchased 
    # + return - OK 
    resource isolated function post payment(Pet payload) returns http:Response|error {
        string resourcePath = string `/payment`;
        http:Request request = new;
        request.setPayload(payload, "application/octet-stream");
        http:Response response = check self.clientEp->post(resourcePath, request);
        return response;
    }
```
After applying the change 
```ballerina
# Creates a new user.
    #
    # + return - OK 
    resource isolated function post user(byte[] payload) returns http:Response|error {
        string resourcePath = string `/user`;
        http:Request request = new;
        request.setPayload(payload, "application/octet-stream");
        http:Response response = check self.clientEp->post(resourcePath, request);
        return response;
    }
    # Creates a new payment.
    #
    # + payload - Details of the pet to be purchased 
    # + return - OK 
    resource isolated function post payment(byte[] payload) returns http:Response|error {
        string resourcePath = string `/payment`;
        http:Request request = new;
        request.setPayload(payload, "application/octet-stream");
        http:Response response = check self.clientEp->post(resourcePath, request);
        return response;
    }
```

## Automation tests
 - Unit tests - added
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-cli/src/test/java/io/ballerina/openapi/generators/client/RequestBodyTests.java [hunk 1]
```diff
@@ -318,6 +318,22 @@ public void testRequestBodyWithReference() throws IOException, BallerinaOpenApiE
         compareGeneratedSyntaxTreeWithExpectedSyntaxTree(expectedPath, syntaxTree);
     }
 
+    @Test
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/java/io/ballerina/openapi/generators/client/RequestBodyTests.java:321]: Lets add the description

**Review by NipunaRanasinghe — APPROVED** [review]

**Review by aneeshafedo — APPROVED** [review]
