### PR TITLE
Fix issue with generating duplicate OAS for build `--export-openapi` flag

### LINKED ISSUE #787: OpenAPI build extension generate duplicate OAS for multiple service node in same ballerina file
**Description:**

```ballerina file 
import ballerina/http;

listener http:Listener backendEP01 = check new(8080);
listener http:Listener backendEP02 = check new(8081);
service /v1 on backendEP01 {
    resource function get mock(@http:Payload json payload) returns string {
        return "Mock2 resource was invoked.";
    }
}
service /v1 on backendEP02 {
    resource function get .() returns string {
        return "Mock1 resource was invoked.";
    }
}
```
This ballerina file build option generate duplicate yaml file 
**Steps to reproduce:**
> bal build --export-openapi
**Affected Versions:**
Beta6 RC1
**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-build-extension/src/main/java/io/ballerina/openapi/build/HttpServiceAnalysisTask.java [hunk 1]
```diff
@@ -89,28 +104,82 @@ public void perform(SyntaxNodeAnalysisContext context) {
...
+                            allServices.add(service);
+                        }
+                        services.put(serviceSymbol.get().hashCode(), updateServiceName);
+                    }
                 }
             }
         }
     }
 }
+
```
Comment (NipunaRanasinghe) [inline openapi-build-extension/src/main/java/io/ballerina/openapi/build/HttpServiceAnalysisTask.java:185]: Additional new line?

**Review by NipunaRanasinghe — APPROVED** [review]
LGTM
