### PR TITLE
[BallerinaToOAS][beta6] Fix issue with generated OAS for record field has array record with nullable

### LINKED ISSUE #869: Issue with generated OAS for record field has array record with nullable
**Description:**
```ballerina
type ResponseError record {|
    int? id;
    ResponseError[]? resError;
|};

type ResponseError record {|
    int? id;
    ResponseError[]? resError?;
|};
```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java [hunk 1]
```diff
@@ -352,19 +342,46 @@ private void mapArrayToArraySchema(Map<String, Schema> schema, RecordFieldSymbol
...
             } else if (typeSymbol.typeKind() != TypeDescKind.NIL) {
                 symbolProperty = ConverterCommonUtils.getOpenApiSchema(typeSymbol.typeKind().getName());
             }
         }
         return symbolProperty;
     }
 
+    /**
+     * This util function is to handle the type reference symbol is record type or enum type.
+     *
```
Comment (NipunaRanasinghe) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIComponentMapper.java:366]: Additional new line

**Review by NipunaRanasinghe — APPROVED** [review]
Approved with a minor suggestion
