### PR TITLE
[Validator] Fix issue returning wrong validation for resource has root path `.`

### LINKED ISSUE #891: Validator return wrong validation for  resource has root path `.`
**Description:**
```ballerina
service /v1 on new http:Listener(9090) {
    resource function get .() returns string {
        ...
    }
}
```
Related openapi path `/`

```openapi
paths:
  /:
    get:
      summary: List all pets
      ...
```

**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests  - add
   > Code coverage information
 - Integration tests - add
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-integration-tests/src/test/java/io/ballerina/openapi/extension/build/ValidatorTests.java [hunk 1]
```diff
@@ -204,4 +204,25 @@ public void typeMisMatchingInRecord() throws IOException {
...
         }
     }
+
+    @Test(description = "Validator for resource path has root path '.'")
+    public void validatorWithRootPath() throws IOException {
+        List<String> buildArgs = new LinkedList<>();
+        buildArgs.add("project_8");
+        InputStream successful = TestUtil.executeOpenapiBuild(DISTRIBUTION_FILE_NAME, TEST_RESOURCE, buildArgs);
+        String msg = "ERROR [service.bal:(12:30,12:36)] Type mismatch with parameter 'id' for the" +
+                " method 'get' of the path '/'.In OpenAPI contract its type is 'string' and resources type is 'int'.";
```
Comment (NipunaRanasinghe) [inline openapi-integration-tests/src/test/java/io/ballerina/openapi/extension/build/ValidatorTests.java:214]: Shall we reword the error messages in a clearer way? (similar to what we did in https://github.com/ballerina-platform/openapi-tools/pull/893#discussion_r808152640)

File: openapi-integration-tests/src/test/java/io/ballerina/openapi/extension/build/ValidatorTests.java [hunk 2]
```diff
@@ -204,4 +204,25 @@ public void typeMisMatchingInRecord() throws IOException {
...
+        try (BufferedReader br = new BufferedReader(new InputStreamReader(successful))) {
+            Stream<String> logLines = br.lines();
+            String generatedLog = logLines.collect(Collectors.joining(System.lineSeparator()));
+            logLines.close();
+            generatedLog = (generatedLog.trim()).replaceAll(WHITESPACE_PATTERN, "");
+            msg = (msg.trim()).replaceAll(WHITESPACE_PATTERN, "");
+            if (generatedLog.contains(msg)) {
+                Assert.assertTrue(true);
+            } else {
+                Assert.fail("OpenAPIValidator execution fail.");
```
Comment (NipunaRanasinghe) [inline openapi-integration-tests/src/test/java/io/ballerina/openapi/extension/build/ValidatorTests.java:224]:
```suggestion
                Assert.fail("OpenAPIValidator execution failed.");
```

File: openapi-integration-tests/src/test/java/io/ballerina/openapi/extension/build/ValidatorTests.java [hunk 3]
```diff
@@ -204,4 +204,25 @@ public void typeMisMatchingInRecord() throws IOException {
             }
         }
     }
+
+    @Test(description = "Validator for resource path has root path '.'")
```
Comment (NipunaRanasinghe) [inline openapi-integration-tests/src/test/java/io/ballerina/openapi/extension/build/ValidatorTests.java:208]:
```suggestion
    @Test(description = "Test to assert validator errors for resources having the root path ('.')")
```

File: openapi-validator/src/main/java/io/ballerina/openapi/validator/ResourceWithOperation.java [hunk 4]
```diff
@@ -288,37 +291,45 @@
...
         }
         return resourceSummaryList;
     }
 
+    /**
+     * This function generates resource function path that align to OAS format.
+     */
+    private static String generatePath(NodeList<Node> nodes, Map<String, Node> parameterNodeMap) {
+        StringBuilder pathBuilder = new StringBuilder();
+        pathBuilder.append(SLASH);
```
[the remark this answers is not in the document]
Comment (lnash94) [reply openapi-validator/src/main/java/io/ballerina/openapi/validator/ResourceWithOperation.java:315]: Yeah, This won't be affected to the OS-specific since we take details from directly OpenAPI contract to compare with syntax tree and OAS allows to user to document the path with forwarding slash `/` only. Here what we do is traverse the syntax node for generating path which aligns to the OpenAPI path format. 🙂

File: openapi-integration-tests/src/test/java/io/ballerina/openapi/extension/build/ValidatorTests.java (hunk 1 above)
Comment (lnash94) [reply openapi-integration-tests/src/test/java/io/ballerina/openapi/extension/build/ValidatorTests.java:214]: Yeah sure, Currently I'm rewording all the validator error messages with this issue https://github.com/ballerina-platform/openapi-tools/issues/910. Shall I address this via the fix from it? WDYT? 🙂
