### PR TITLE
[BallerinaToOpenAPI] Fix Invalid media type error is thrown when a resource method return type is a qualified name reference

### LINKED ISSUE #832: Invalid media type error is thrown when a resource method return type is a qualified name reference
**Description:**
Consider the following snippet:
```ballerina

service /products on new http:Listener(8080) {

    private map<types:Product> products = {};

    # List all products
    # + return - List of products
    resource function get .() returns types:Product[] {
        return self.products.toArray();
    }
}
```
When generating OpenAPI specification, the following error is printed:
```
ERROR [main.bal:(10:5,14:6)] Invalid mediaType: qualified
```
The OpenAPI yaml is generated without the above method.

Complete source can be found at https://github.com/IMS94/ballerina_examples/blob/master/crud_service/main.bal. In this complete example, I get all the other resource methods in the yaml except for the GET (list all) request.

**Steps to reproduce:**
See description.

**Affected Versions:**
Swan Lake GA Snapshot Build 1

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests - add
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

### CODE REVIEW

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java [hunk 1]
```diff
@@ -465,6 +465,16 @@ private void setCacheConfigField(CacheConfigAnnotation cacheConfig, String field
...
+        } else if (array.memberTypeDesc().kind() == QUALIFIED_NAME_REFERENCE) {
+            Optional<ApiResponses> optionalAPIResponses =
+                    handleQualifiedNameType(new ApiResponses(), customMediaPrefix, headers, apiResponse,
+                            (QualifiedNameReferenceNode) array.memberTypeDesc());
+            if (optionalAPIResponses.isPresent()) {
+                ApiResponses responses = optionalAPIResponses.get();
+                updateResponseWithArraySchema(responses);
+                apiResponses.putAll(responses);
+            }
+            return Optional.of(apiResponses);
```
Comment (IMS94) [inline openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java:477]: I think we don't need this return statement since we have a return after the `else` condition.

**Review by IMS94 — APPROVED** [review]
LGTM! There's a minor comment.

File: openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java (hunk 1 above)
Comment (lnash94) [reply openapi-bal-service/src/main/java/io/ballerina/openapi/converter/service/OpenAPIResponseMapper.java]: yeah , will remove

**Review by IMS94 — APPROVED** [review]

**Review by NipunaRanasinghe — APPROVED** [review]
