### PR TITLE
[1.4.x]Fix for OpenAPI spec generation when display annotations are used

### LINKED ISSUE #1212: OpenAPI spec is invalid when display annotations are used
**Description:**
$subject. The spec generated via the tool does not have the `info` flag if the service has a display annotation tagged to it.

Refer sample below for the spec generated for https://github.com/SumayyaZiyad/TestSingleRESTComponent/tree/main/SampleRest2

```
openapi: 3.0.1
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /greeting:
    get:
      summary: A resource for generating greetings
      operationId: getGreeting
      parameters:
      - name: name
        in: query
        description: the input string name
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: Found unexpected output
          content:
            text/plain:
              schema:
                type: string
components: {}
```

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-integration-tests/src/test/java/io/ballerina/openapi/cmd/BallerinaToOpenAPITests.java [hunk 1]
```diff
@@ -125,6 +125,23 @@ public void nonHttpService() throws IOException, InterruptedException {
...
+    public void nonOpenAPIAnnotationWithSlash() throws IOException, InterruptedException {
+        executeCommand("project_non_openapi_annotation_with_base_path/service.bal", "payload_openapi.yaml",
+                "project_non_openapi_annotation_with_base_path/result.yaml");
+    }
+
+    @Test(description = "Service is with non openapi annotation and without a base path")
+    public void nonOpenAPIAnnotationWithWithoutBasePath() throws IOException, InterruptedException {
+        executeCommand("project_non_openapi_annotation_without_base_path/service.bal", "payload_openapi.yaml",
+                "project_non_openapi_annotation_without_base_path/result.yaml");
+    }
```
Comment (NipunaRanasinghe) [inline openapi-integration-tests/src/test/java/io/ballerina/openapi/cmd/BallerinaToOpenAPITests.java:144]: Missing newline

**Review by NipunaRanasinghe — APPROVED** [review]
Approved with a minor suggestion
