### PR TITLE
Fix for checking constraint value is non zero 

### LINKED ISSUE #1050: Generated constraint has compilation issue when the validation values has 0
**Description:**
$subject
```openapi
  schemas:
    Address:  
      type: string
      minLength: 0
    Person:
      type: object
      required:
        - id
      properties:
        name:
          type: string
          maxLength: 14 
        hobby:
          type: array
          items:
            type: string
          maxItems: 5
          minItems: 0
        id:
          type: integer
          maximum: 5
        address:  
          $ref: "#/components/schemas/Address"
        salary:
          type: number
          format: float
          maximum: 0
        net:
          type: number
          exclusiveMinimum: true
          minimum: 0 # minimum has zero
```
expected code generator
```ballerina
import ballerina/constraint;

public type Address string;

public type Person record {
    @constraint:String {maxLength: 14}
    string name?;
    @constraint:Array {maxLength: 5}
    string[] hobby?;
    @constraint:Int {maxValue: 5}
    int id;
    Address address?;
    float salary?;
    decimal net?;
};
```
**Steps to reproduce:**

**Affected Versions:**

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Review by NipunaRanasinghe — APPROVED** [review]

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/TypeGeneratorUtils.java [hunk 1]
```diff
@@ -312,25 +313,31 @@ private static AnnotationNode generateArrayConstraint(ArraySchema arraySchema) {
 
     private static List<String> getNumberAnnotFields(Schema<?> numberSchema) {
         List<String> fields = new ArrayList<>();
-        if (numberSchema.getMinimum() != null && numberSchema.getExclusiveMinimum() == null) {
+
+        if ((numberSchema.getMinimum() != null) &&
+                (BigDecimal.ZERO.compareTo(numberSchema.getMinimum()) != 0)
+                && (numberSchema.getExclusiveMinimum() == null)) {
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/TypeGeneratorUtils.java:319]:
```suggestion
        if (numberSchema.getMinimum() != null &&
                BigDecimal.ZERO.compareTo(numberSchema.getMinimum()) != 0
                && numberSchema.getExclusiveMinimum() == null) {
```

Comment (NipunaRanasinghe) [reply openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/TypeGeneratorUtils.java:319]: Please correct all the other similar places

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/TypeGeneratorUtils.java [hunk 2]
```diff
@@ -312,25 +313,31 @@ private static AnnotationNode generateArrayConstraint(ArraySchema arraySchema) {
...
+                numberSchema.getExclusiveMinimum() && numberSchema.getMinimum() != null &&
+               (BigDecimal.ZERO.compareTo(numberSchema.getMinimum()) != 0)) {
             String value = numberSchema.getMinimum().toString();
             String fieldRef = EXCLUSIVE_MIN + COLON + value;
             fields.add(fieldRef);
         }
         if (numberSchema.getExclusiveMaximum() != null &&
                 numberSchema.getExclusiveMaximum() &&
-                numberSchema.getMaximum() != null) {
+                numberSchema.getMaximum() != null && (BigDecimal.ZERO.compareTo(numberSchema.getMaximum()) != 0)) {
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/TypeGeneratorUtils.java:340]: Can't we just use `numberSchema.getMaximum() != 0` in here?

Comment (lnash94) [reply openapi-cli/src/main/java/io/ballerina/openapi/generators/schema/TypeGeneratorUtils.java:340]: We cannot do it because `numberSchema.getMaximum() ` gives a big decimal value that does not support the `!=` operator.

**Review by NipunaRanasinghe — APPROVED** [review]
LGTM
