### PR TITLE
[Service]Fix for supporting to `application/x-www-form-urlencoded` media type in request body for service generation

### LINKED ISSUE #929: Provide support for `application/x-www-form-urlencoded` media type in request body for service generation
**Description:**

**Request Body with URL encode**
- [x] With inline record schema in the request body
```openapi
openapi: 3.0.1
info:
  title: testInlineRequestBody
  version: 1.0.0
paths:
  /user:
    post:
      summary: Post operation for the path /user
      operationId: addUser
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                userName:
                  description: User Name
                  type: string
                userPhone:
                  description: User Phone Number
                  type: string
              required:
                - userName
                - userPhone
      responses:
        200:
          description: Successful
          content:
            application/json:
              example: Ok
components: {}
```
Inswagger parser automatically moves the inline object to component schema then finally it behaves like Reference schema scenarios.

- [x]  with reference schema  request body
```openapi
openapi: 3.0.1
info:
  title: testInlineRequestBody
  version: 1.0.0
paths:
  /user:
    post:
      summary: Post operation for the path /user
      operationId: addUser
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: Successful
          content:
            application/json:
              example: Ok
components: 
  schemas:
    User:
     type: object
     properties:
        userName:
          description: User Name
          type: string
        userPhone:
          description: User Phone Number
          type: string
          required:
                - userName
                - userPhone

```
ballerina code
```ballerina
resource function post user(@http:Payload {mediaType: "application/x-www-form-urlencoded"}  User payload) returns json {   
    }
```
- [x] without  schema  in the request body
```openapi
openapi: 3.0.1
info:
  title: testInlineRequestBody
  version: 1.0.0
paths:
  /user:
    post:
      summary: Post operation for the path /user
      operationId: addUser
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema: {}
      responses:
        200:
          description: Successful
          content:
            application/json:
              example: Ok
```
ballerina code 
```ballerina 
resource function post user(@http:Payload {mediaType: "application/x-www-form-urlencoded"} map<string> payload) returns json {   
    }
```

### PR DESCRIPTION
**Pull request by lnash94**
## Automation tests
 - Unit tests - add
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java [hunk 1]
```diff
@@ -76,30 +79,26 @@
...
+            SeparatedNodeList<MappingFieldNode> fields = fillRequestAnnotationValues(literals, equalDataType);
+            annotValue = NodeFactory.createMappingConstructorExpressionNode(
+                    createToken(SyntaxKind.OPEN_BRACE_TOKEN), fields, createToken(SyntaxKind.CLOSE_BRACE_TOKEN));
+        } else {
+            Iterator<Map.Entry<String, MediaType>> content = requestBody.getContent().entrySet().iterator();
+            Map.Entry<String, MediaType> mime = content.next();
+            equalDataType.add(mime);
+            typeName = getNodeForPayloadType(components, mime);
+            if (mime.getKey().equals(APPLICATION_URL_ENCODE)) {
+                SeparatedNodeList<MappingFieldNode> fields = fillRequestAnnotationValues(literals, equalDataType);
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java:98]: Is there any a particular reason not to use streaming APIs, instead of using this iterator?

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java [hunk 2]
```diff
@@ -115,50 +114,72 @@ private TypeDescriptorNode getNodeForPayloadType(Components components, Map.Entr
...
-                                createToken(SyntaxKind.OPEN_BRACKET_TOKEN), null,
-                                createToken(SyntaxKind.CLOSE_BRACKET_TOKEN));
-                        typeName = createArrayTypeDescriptorNode(createBuiltinSimpleNameReferenceNode(
-                                        null, createIdentifierToken(GeneratorConstants.BYTE)),
-                                NodeFactory.createNodeList(dimensionNode));
-                        break;
-                    case APPLICATION_JSON:
-                    default:
+            String mediaTypeContent = mediaType.getKey().trim();
+            if (mediaTypeContent.matches("text/.*")) {
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java:118]: Shall we have a common constant for this regex pattern?

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java [hunk 3]
```diff
@@ -115,50 +114,72 @@ private TypeDescriptorNode getNodeForPayloadType(Components components, Map.Entr
...
+                    ArrayDimensionNode dimensionNode = NodeFactory.createArrayDimensionNode(
+                            createToken(SyntaxKind.OPEN_BRACKET_TOKEN), null,
+                            createToken(SyntaxKind.CLOSE_BRACKET_TOKEN));
+                    typeName = createArrayTypeDescriptorNode(createBuiltinSimpleNameReferenceNode(
+                                    null, createIdentifierToken(GeneratorConstants.BYTE)),
+                            NodeFactory.createNodeList(dimensionNode));
+                    break;
+                case APPLICATION_JSON:
+                    Schema<?> schema = components.getSchemas().get(schemaName);
+                    // This condition is avoid to wrong code generation for union type request body. If given schema
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java:141]:
```suggestion
                    // This condition is to avoid wrong code generation for union type request body. If given schema
```

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java [hunk 4]
```diff
@@ -115,50 +114,72 @@ private TypeDescriptorNode getNodeForPayloadType(Components components, Map.Entr
...
+     *  01. when field has some override media type
+     *  <pre> @http:Payload{mediaType: "application/x-www-form-urlencoded"} User payload</pre>
+     *  02. when field has list media value
+     *  <pre> @http:Payload{mediaType: ["application/json", "application/snowflake+json"]} User payload</pre>
+     *
+     */
+    private SeparatedNodeList<MappingFieldNode> fillRequestAnnotationValues(List<Node> literals,
                                                                             HashSet<Map.Entry<String,
                                                                                     MediaType>> equalDataType) {
+        Token comma = createToken(SyntaxKind.COMMA_TOKEN);
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java:178]: Shall we remove this variable since its not being used?

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java [hunk 5]
```diff
@@ -167,10 +188,18 @@ private TypeDescriptorNode getNodeForPayloadType(Components components, Map.Entr
         }
         literals.remove(literals.size() - 1);
         SeparatedNodeList<Node> expression = NodeFactory.createSeparatedNodeList(literals);
-        ListConstructorExpressionNode valueExpr = NodeFactory.createListConstructorExpressionNode(
-                createToken(SyntaxKind.OPEN_BRACKET_TOKEN), expression, createToken(SyntaxKind.CLOSE_BRACKET_TOKEN));
-        SpecificFieldNode specificFieldNode = NodeFactory.createSpecificFieldNode(null, mediaType,
-                createToken(SyntaxKind.COLON_TOKEN), valueExpr);
+        if (equalDataType.size() == 1) {
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java:191]: Can this also be more than 1? if so, `equalDataTypes` would be a better choice for the name

File: openapi-cli/src/test/resources/generators/service/swagger/requestBody/url_form_encode.yaml [hunk 6]
```diff
@@ -0,0 +1,72 @@
...
+        type: object
+        properties:
+          userName:
+            description: User Name
+            type: string
+          password:
+            description: User Phone Number
+            type: string
+            required:
+              - userName
```
Comment (NipunaRanasinghe) [inline openapi-cli/src/test/resources/generators/service/swagger/requestBody/url_form_encode.yaml:72]: missing EOF new line

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java (hunk 1 above)
Comment (lnash94) [reply openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java:98]: Here we didn't iterate all the elements in the Map set. Our intention is to pick the first element from mediaType. To achieve this  I used the first iteration there. since we are unable to predict the key for picking the value directly taken. 🙂

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java (hunk 5 above)
Comment (lnash94) [reply openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java]: yeah, it can be, I will change the parameter name.

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java (hunk 4 above)
Comment (lnash94) [reply openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java:179]: This is used inside the while loop, in line 188 🙂

File: openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java (hunk 1 above)
Comment (NipunaRanasinghe) [reply openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java:99]: I'm not sure why we don't need to consider the other elements apart from the first element. Also, is this a ordered map (i.e. `LinkedHashMap`)? Otherwise we cant guarantee on the order right?

Comment (lnash94) [reply openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java:99]: This is the scenario we are going to address here 
```openapi
paths:
  /pets:
    post:
      summary: Add a new pet
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
          application/xml:
            schema:
              $ref: '#/components/schemas/PetList'
          text/plain:
            schema:
              type: string
```
Here request body has multiple mediaType and those media types map to different payload types. In ballerina, currently, we have no way to support these multiple behaviours, Therefore we go with the first media type and its payload type for the resource function request body details.  That is why we pick the first element here. 🙂 
When come to access it in openapi spec parser `requestBody.getContent()` give output as [`Content`](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-models/src/main/java/io/swagger/v3/oas/models/media/Content.java) type object its extend from `LinkedHashMap<String, MediaType>` . Yeah it is ordered map. 🙂

Comment (NipunaRanasinghe) [reply openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java:99]: Hmmm it makes sense.. In that case shouldn't we have at-least a warning, mentioning that we ignoring the other types?

Comment (lnash94) [reply openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java:99]: Yeah it would be great to have warning , I will add a warning there :)

Comment (lnash94) [reply openapi-cli/src/main/java/io/ballerina/openapi/generators/service/RequestBodyGenerator.java:99]: I will address warning via this issue https://github.com/ballerina-platform/openapi-tools/issues/942 :)

File: openapi-cli/src/test/resources/generators/service/swagger/requestBody/url_form_encode.yaml [hunk 7]
```diff
@@ -0,0 +1,72 @@
...
+            application/json:
+              example: Ok
+  /user03:
+    post:
+      summary: Post operation for the path /user
+      operationId: noSchema
+      requestBody:
+        content:
+          application/x-www-form-urlencoded:
+            schema: {}
```
Comment (shafreenAnfar) [inline openapi-cli/src/test/resources/generators/service/swagger/requestBody/url_form_encode.yaml:53]: Is this the best way to say the request body can only be key/value pairs ?

Comment (lnash94) [reply openapi-cli/src/test/resources/generators/service/swagger/requestBody/url_form_encode.yaml:53]: yeah we can use `type: object`  with  the `additionalProperties`  keyword to specify the type of values in key/value pairs. 
```
schema:
   type: object
   additionalProperties:
        type: string
```
This represents the map<string> with respect to the ballerina language.  [reference](https://swagger.io/docs/specification/data-models/dictionaries/#:~:text=Dictionaries%2C%20HashMaps%20and%20Associative%20Arrays)

Comment (shafreenAnfar) [reply openapi-cli/src/test/resources/generators/service/swagger/requestBody/url_form_encode.yaml:53]: +1 for this.

**Review by shafreenAnfar — APPROVED** [review]
Went through the test-cases and LGTM!

**Review by NipunaRanasinghe — APPROVED** [review]
LGTM
